production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: property
  username: property
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: property_test
  username: property
  password:
